version: '2'
networks:
  default:
    external:
      name: int221-network
services:
  backend:
    build: .
    image: ghcr.io/int221-integrated-project/int221-backend
    environment:
      SERVICE_VERSION: v1
    volumes:
      - ~/Images:/public/images

